

# site icon
favicon: /favicon.png

# author headimg
headimg: https://imgchr.github.la/steve.jpeg
# author info
name: ぱないの
description: freelancer

# search
search: 
    enable: true
    placeholder: Enter Key...

# sidebar
sidebar: 
  enable: true
  menus:
    -
      name: tumbler
      link: https://www.tumblr.com/
      target: _blank
    -
      name: Netlify
      link: https://www.netlify.com/
      target: _blank



# count(统计)
count:
  enable: true

# comments
comments:
  duoshuo_username:  
  #disqus_username: 

# accounts support weibo/github/zhihu/twitter/douban 
# display to former three
social: 
  -
    name: weibo
    link: http://weibo.com/
  -
    name: github
    link: https://github.com/
  -
    name: zhihu
    link: https://www.zhihu.com/
  -
    name: twitter
    link: 
  -
    name: douban
    link: 





